### ISSUE TITLE
existing module

### ISSUE THREAD

**Issue by binford2k** [flypenguin/puppet-mkdir#2]
You might be interested in this resource type. https://github.com/puppetlabs/pltraining-dirtree#dirtree-resource-type

**Comment by flypenguin** [comment]
I didnt know about this one. Thanks! Still, I won't delete mine, I'm using
it quite often ;)

2015-12-01 2:59 GMT+01:00 Ben Ford notifications@github.com:

**Comment by flypenguin** [comment]
So, I just had a look at `dirtree`, and it does not do the same as my module. Dirtree has one function (`dirtree` :), while I have none. You can probably do the same with both modules, but I like mine more (of course ;) because you can do multiple `mkdir::p` for the same path without interfering with other modules, basically. So this nicely solves the issue that maybe two modules want to create the same path, which is happening more often than I'd like to.

**Comment by binford2k** [comment]
It has a function and a resource type. The resource type literally does a ruby mkdir -p. The function is for generating an array, should you want to manage file resources for parent directories.
